version: '3.5'
services:
  discovery:
    image: services/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  user-service:
    image: services/user-service
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3336:3336"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  book-service:
    image: services/book-service
    container_name: book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - "3335:3335"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
        - discovery